import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { AlertTriangle, CandlestickChart, FlaskConical, Scale, ShieldCheck, type LucideIcon } from "lucide-react";
import { PerformanceBackdrop } from "@/components/site/backdrops";
import PaperRecord from "@/components/site/PaperRecord";
import { useRouteMeta } from "@/site/seo";
import { routeFor, prefetchRoute } from "@/site/routes";
import { cn } from "@/lib/utils";

const EASE = [0.22, 1, 0.36, 1] as const;

/**
 * /performance — what is actually known about performance, and nothing else.
 *
 * This page used to show an equity curve, a month-by-month grid, 612 trades at
 * a 44% hit rate, attribution by strategies that do not exist and execution
 * quality for live routing that is not switched on. The curve and the grid
 * were generated by a seeded random-number generator. None of it was a result.
 *
 * What replaces it is the platform's own recorded validation
 * (STRATEGY_VALIDATION_REPORT.md, 2026-08-13): no strategy has a verified
 * positive edge. Every figure below is copied from that report, and the method
 * cards describe only what the code does (services/fill_model.py,
 * services/validation.py, services/forward_validation.py). Forward paper
 * records appear under "Forward paper record" only when the owner publishes a
 * Trading Instance, straight from its ledger (GET /public/track-record).
 */

interface Verdict {
  strategy: string;
  result: string;
  detail: string;
  decision: "FAILED" | "INSUFFICIENT EVIDENCE";
}

// STRATEGY_VALIDATION_REPORT.md, "Executive decision" — untouched, pooled,
// real-data test set, 5-minute timeframe. Copied, not rounded.
const VERDICTS: Verdict[] = [
  { strategy: "Supertrend 1.0.0", result: "−6.118R", detail: "PF 0.635 · 29.41% wins over 17 trades", decision: "FAILED" },
  { strategy: "Donchian Breakout 1.0.0", result: "−12.704R", detail: "PF 0.420 · 26.32% wins over 19 trades", decision: "FAILED" },
  { strategy: "Decision Brain 1.0.0", result: "−2.976R", detail: "PF 0.806 · 33.33% wins over 15 trades", decision: "INSUFFICIENT EVIDENCE" },
];

interface Method {
  icon: LucideIcon;
  title: string;
  body: string;
}

const METHOD: Method[] = [
  {
    icon: FlaskConical,
    title: "An untouched test set",
    body: "Strategies are judged on data held back from every choice made while building them. A result on data the strategy was tuned on is not evidence.",
  },
  {
    icon: Scale,
    title: "Costs in every simulated fill",
    body: "Every simulated fill pays a fee — 0.04% taker, 0.02% maker. Market and stop orders also pay half of a 0.04% spread plus 0.03% slippage; resting limit entries fill at their price, as they would on an exchange.",
  },
  {
    icon: CandlestickChart,
    title: "Closed candles only",
    body: "Decisions are made on completed candles. The forming candle is shown on charts but never traded, so a backtest cannot peek at a bar that has not finished.",
  },
  {
    icon: ShieldCheck,
    title: "Forward paper before anything else",
    body: "A strategy that clears testing then runs on live Binance market data with simulated fills, every decision journaled. Live order routing stays locked.",
  },
];

function Section({ eyebrow, title, children, className }: {
  eyebrow: string; title: string; children: React.ReactNode; className?: string;
}) {
  return (
    <section className={cn("container-x mt-20 sm:mt-28", className)}>
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: "-80px" }}
        transition={{ duration: 0.55, ease: EASE }}
      >
        <span className="font-mono text-[11px] uppercase tracking-[0.18em] text-emerald-soft">{eyebrow}</span>
        <h2 className="mt-3 text-balance text-2xl font-bold tracking-tight text-white sm:text-3xl">{title}</h2>
      </motion.div>
      <div className="mt-8">{children}</div>
    </section>
  );
}

export default function PerformancePage() {
  const route = routeFor("/performance")!;
  useRouteMeta(route);

  return (
    <>
      <PerformanceBackdrop />

      {/* ── Hero ────────────────────────────────────────────────────────── */}
      <section className="container-x pt-32 sm:pt-40">
        <motion.span
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: EASE }}
          className="inline-flex items-center gap-2 rounded-full border border-emerald/30 bg-emerald/[0.07] px-3 py-1 font-mono text-[11px] uppercase tracking-[0.18em] text-emerald-soft"
        >
          Performance
        </motion.span>
        <motion.h1
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.06, ease: EASE }}
          className="mt-6 max-w-3xl text-balance text-4xl font-extrabold leading-[1.05] tracking-tight text-white sm:text-5xl"
        >
          No verified edge <span className="text-loss-soft">— yet.</span>
        </motion.h1>
        <motion.p
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.14, ease: EASE }}
          className="mt-6 max-w-2xl text-[17px] leading-relaxed text-white/60"
        >
          Nexus does not publish a performance figure it cannot back. Our own validation found no
          strategy with a verified positive edge, so this page shows that result instead of a
          curve. Numbers will appear here when forward paper trading on live data supports them —
          with the sample, the period and the costs beside them.
        </motion.p>
      </section>

      {/* ── What validation found ──────────────────────────────────────── */}
      <Section eyebrow="Recorded validation · 2026-08-13" title="What our own testing found">
        <div className="overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.02]">
          {VERDICTS.map((v, i) => (
            <motion.div
              key={v.strategy}
              initial={{ opacity: 0, y: 10 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-40px" }}
              transition={{ duration: 0.45, delay: i * 0.07, ease: EASE }}
              className="grid gap-2 border-b border-white/[0.06] px-5 py-4 last:border-b-0 sm:grid-cols-[1.2fr_0.7fr_1.4fr_auto] sm:items-center sm:gap-6"
            >
              <span className="font-medium text-white">{v.strategy}</span>
              <span className="font-mono text-lg font-semibold text-loss-soft">{v.result}</span>
              <span className="text-sm text-white/50">{v.detail}</span>
              <span
                className={cn(
                  "w-fit rounded-md border px-2 py-0.5 font-mono text-[10px] uppercase tracking-wider",
                  v.decision === "FAILED"
                    ? "border-loss/40 bg-loss/10 text-loss-soft"
                    : "border-gold/40 bg-gold/10 text-gold-soft",
                )}
              >
                {v.decision}
              </span>
            </motion.div>
          ))}
        </div>
        <p className="mt-4 max-w-3xl text-sm leading-relaxed text-white/45">
          Untouched, pooled, real-data test set on the 5-minute timeframe. R is the initial risk
          unit: at the 0.5% risk assumption, 1R is 0.5% of starting equity. None of these results
          authorises live trading or supports a profitability claim — and a strategy marked
          “insufficient evidence” has not shown an edge, it has only not been ruled out.
        </p>
      </Section>

      {/* ── Forward paper ──────────────────────────────────────────────── */}
      <Section eyebrow="Forward paper · live Binance data" title="Forward paper record">
        <PaperRecord />
      </Section>

      {/* ── Method ─────────────────────────────────────────────────────── */}
      <Section eyebrow="Method" title="How a result would earn a place on this page">
        <div className="grid gap-4 sm:grid-cols-2">
          {METHOD.map((m, i) => (
            <motion.div
              key={m.title}
              initial={{ opacity: 0, y: 14 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-60px" }}
              transition={{ duration: 0.45, delay: i * 0.06, ease: EASE }}
              className="rounded-2xl border border-white/[0.08] bg-white/[0.02] p-5"
            >
              <m.icon className="h-5 w-5 text-emerald-soft" />
              <h3 className="mt-3 text-[15px] font-semibold text-white">{m.title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-white/50">{m.body}</p>
            </motion.div>
          ))}
        </div>
      </Section>

      {/* ── Risk ───────────────────────────────────────────────────────── */}
      <section className="container-x mt-20 pb-24 sm:mt-28">
        <div className="flex gap-4 rounded-2xl border border-loss/25 bg-loss/[0.05] p-5 sm:p-6">
          <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-loss-soft" />
          <div>
            <h2 className="text-[15px] font-semibold text-white">Trading carries risk of loss</h2>
            <p className="mt-2 text-sm leading-relaxed text-white/55">
              Past or simulated results do not predict future ones, and simulated fills are an
              estimate of what a venue would have done. Read the{" "}
              <Link
                to="/risk-disclosure"
                onPointerEnter={() => prefetchRoute("/risk-disclosure")}
                className="text-white underline decoration-white/30 underline-offset-2 hover:decoration-white"
              >
                risk disclosure
              </Link>{" "}
              before relying on anything here.
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
